/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface MainContentProps {
  children: React.ReactNode;
}

const MainContent: React.FC<MainContentProps> = ({ children }) => {
  return (
    <main className="w-full overflow-hidden">
      {children}
    </main>
  );
};

export default MainContent;
