/**
 * This code was generated by Builder.io.
 */
import React from "react";
import UnreadNotification from "./UnreadNotification";

const App: React.FC = () => {
  return (
    <main>
      <UnreadNotification count={2} />
    </main>
  );
};

export default App;
