/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface NotificationHeaderProps {
  title: string;
}

const NotificationHeader: React.FC<NotificationHeaderProps> = ({ title }) => {
  return (
    <header className="flex justify-between items-center">
      <h3 className="font-semibold text-[11px] text-app-primary-2 truncate mr-2">{title}</h3>
    </header>
  );
};

export default NotificationHeader;
