/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface UnreadNotificationProps {
  count: number;
}

const UnreadNotification: React.FC<UnreadNotificationProps> = ({ count }) => {
  return (
    <div className="absolute -top-1 -right-1 bg-red-500 text-white text-[9px] font-bold rounded-full w-5 h-5 flex items-center justify-center">
      {count}
    </div>
  );
};

export default UnreadNotification;
